name: PHP Quality

on:
  push:
  pull_request:

jobs:
  fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2

      - name: Validate Composer
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHP CS Fixer
        run: composer cs:check
